# Generated by Django 2.2.12 on 2021-12-27 11:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbAdAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_id', models.CharField(max_length=50, verbose_name='Ads ID')),
                ('account_id', models.CharField(max_length=30, verbose_name='Account ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('fb_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth', verbose_name='Social Auth Model')),
            ],
            options={
                'verbose_name': 'Ad Account',
                'verbose_name_plural': 'Ad Accounts',
            },
        ),
        migrations.CreateModel(
            name='InsightData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('days_count', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_api.FbAdAccount', verbose_name='Ad Account')),
            ],
            options={
                'get_latest_by': ['created_at'],
            },
        ),
    ]
